#!/usr/bin/env python3
"""Emit Fig. 3 and Fig. 4 from committed results. No network, no invented points."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # pipeline/
RESULTS = ROOT / "results"
FIG = Path(__file__).resolve().parents[1] / "figures"


def load(name: str) -> dict:
    path = RESULTS / name
    with path.open() as handle:
        return json.load(handle)


def measured_pairs(job_name: str) -> list[tuple[int, float, float]]:
    """Sampled genomes only: position, measured stock wall, cached wall."""
    job = load(f"savings_20261006/{job_name}")
    rows = []
    for genome in job["genomes"]:
        if genome.get("stock_pred_rel_error") is None:
            continue
        rows.append(
            (
                int(genome["position"]),
                float(genome["stock_wall_s"]),
                float(genome["cached_wall_s"]),
            )
        )
    if not rows:
        raise SystemExit(f"no measured stock rows in {job_name}")
    return rows


def coord(rows: list[tuple[float, float]]) -> str:
    return " ".join(f"({x:g}, {y:.16g})" for x, y in rows)


def write_savings() -> None:
    summary = load("savings_summary.json")
    sens = load("savings_sensitivity.json")
    by_col = {job["collection"]: job for job in summary["jobs"]}
    a_pairs = measured_pairs("A_hmmsearch.json")
    b_pairs = measured_pairs("B_hmmsearch.json")

    def series(key: str) -> str:
        parts = []
        for label in ("A", "B"):
            locked = by_col[label]["cumulative"][key]
            parts.append(f"({label}, {locked:.16g})")
        return " ".join(parts)

    def corrected(key: str) -> str:
        parts = []
        for label in ("A", "B"):
            value = sens["collections"][label][key]
            parts.append(f"({label}, {value:.16g})")
        return " ".join(parts)

    text = r"""% Generated by pipeline/paper/scripts/make_figures.py. Do not edit by hand.
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=1.15cm},
  width=0.40\textwidth,
  height=5.4cm,
  tick label style={font=\scriptsize},
  label style={font=\scriptsize},
  legend style={font=\scriptsize, draw=none, fill=none},
  scale only axis,
]
\nextgroupplot[
  xlabel={Genome position},
  ylabel={Wall (s)},
  title={\scriptsize Measured stock and cached wall},
  legend columns=2,
  legend pos=north east,
]
% source: pipeline/results/savings_20261006/A_hmmsearch.json stock_wall_s where stock_pred_rel_error is set
\addplot+[only marks, mark=*, mark size=1.6pt] coordinates {"""
    text += coord([(p, s) for p, s, _c in a_pairs])
    text += r"""};
\addlegendentry{A stock}
% source: pipeline/results/savings_20261006/A_hmmsearch.json cached_wall_s at those positions
\addplot+[only marks, mark=triangle*, mark size=1.8pt] coordinates {"""
    text += coord([(p, c) for p, _s, c in a_pairs])
    text += r"""};
\addlegendentry{A cached}
% source: pipeline/results/savings_20261006/B_hmmsearch.json stock_wall_s where stock_pred_rel_error is set
\addplot+[only marks, mark=square*, mark size=1.5pt] coordinates {"""
    text += coord([(p, s) for p, s, _c in b_pairs])
    text += r"""};
\addlegendentry{B stock}
% source: pipeline/results/savings_20261006/B_hmmsearch.json cached_wall_s at those positions
\addplot+[only marks, mark=diamond*, mark size=1.8pt] coordinates {"""
    text += coord([(p, c) for p, _s, c in b_pairs])
    text += r"""};
\addlegendentry{B cached}

\nextgroupplot[
  ybar,
  bar width=6pt,
  ymin=0,
  ylabel={Cumulative wall speedup},
  symbolic x coords={A, B},
  xtick=data,
  title={\scriptsize Locked imputation and post-hoc correction},
  legend columns=2,
  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,1.18)}, anchor=south},
  enlarge x limits=0.28,
  clip=false,
]
% source: pipeline/results/savings_summary.json cumulative.cum_speedup_wall
\addplot coordinates {"""
    text += series("cum_speedup_wall")
    text += r"""};
\addlegendentry{Locked, no $P$}
% source: pipeline/results/savings_summary.json cumulative.cum_speedup_wall_with_P
\addplot coordinates {"""
    text += series("cum_speedup_wall_with_P")
    text += r"""};
\addlegendentry{Locked, with $P$}
% source: pipeline/results/savings_sensitivity.json cum_speedup_wall
\addplot coordinates {"""
    text += corrected("cum_speedup_wall")
    text += r"""};
\addlegendentry{Corrected, no $P$}
% source: pipeline/results/savings_sensitivity.json cum_speedup_wall_with_P
\addplot coordinates {"""
    text += corrected("cum_speedup_wall_with_P")
    text += r"""};
\addlegendentry{Corrected, with $P$}
\end{groupplot}
\end{tikzpicture}
"""
    (FIG / "fig3_savings.tex").write_text(text)


def write_residuals() -> None:
    t1 = load("reference_fitter_t1.json")
    block = t1["tie_break_residuals"]["r2p"]["tblout"]
    entry = []
    length = []
    for col in ("4", "7"):
        entry.append((col, block[col]["tie_break"]["entry_count"]["max_abs_residual"]))
        length.append(
            (col, block[col]["tie_break"]["total_entry_length"]["max_abs_residual"])
        )

    def coords(rows: list[tuple[str, float]]) -> str:
        return " ".join(f"({col}, {value:.16g})" for col, value in rows)

    text = r"""% Generated by pipeline/paper/scripts/make_figures.py. Do not edit by hand.
\begin{tikzpicture}
\begin{axis}[
  width=0.78\columnwidth,
  height=5.4cm,
  ybar,
  bar width=8pt,
  ymode=log,
  ymin=1e-8,
  ylabel={Max $|$residual$|$},
  symbolic x coords={4, 7},
  xtick=data,
  xlabel={tblout column},
  tick label style={font=\scriptsize},
  label style={font=\scriptsize},
  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,1.08)}, anchor=south},
  legend columns=2,
  clip=false,
  enlarge x limits=0.35,
  scale only axis,
]
% source: pipeline/results/reference_fitter_t1.json tie_break_residuals.r2p.tblout entry_count max_abs_residual
\addplot+[fill=teal!45] coordinates {"""
    text += coords(entry)
    text += r"""};
\addlegendentry{\texttt{entry\_count}}
% source: pipeline/results/reference_fitter_t1.json tie_break_residuals.r2p.tblout total_entry_length max_abs_residual
\addplot+[fill=orange!55] coordinates {"""
    text += coords(length)
    text += r"""};
\addlegendentry{\texttt{total\_entry\_length}}
\end{axis}
\end{tikzpicture}
"""
    (FIG / "fig4_residuals.tex").write_text(text)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    write_savings()
    write_residuals()


if __name__ == "__main__":
    main()
